Logan-PO/logan

.github/workflows/lint-and-test.yml
I think we'd need to do some things in the repo settings to enable this as a GitHub action and make it a required status check, but this would require all tests to pass and linting to pass before a PR can be merged
=> Add GitHub action to lint and run all tests

.github/workflows/deploy.yml
I _believe_ this will work. In order for backend deployment to work though, we'll need to add two secrets to our repo. Check this out for more info: https://docs.github.com/en/actions/reference/encrypted-secrets
We'll need `EB_ACCESS_KEY_ID` and `EB_ACCESS_KEY_SECRET` (I can provide both when you're ready)
=> Set up continuous deployment for the backend and frontend

services/backend/src/assignments-controller.js, services/backend/src/assignments-controller.test.js
created unit tests for assignments-controller.js
=> unit tests for assignments

services/backend/src/tasks-controller.js, services/backend/src/tasks-controller.test.js
added __test_only__ export to tasks_controller
added unit tests for task routes
=> Task tests

services/frontend/README.md, services/frontend/package.json, services/frontend/src/store.js
created a global store class and updated readme to explain briefly how to use it
=> Global store

package-lock.json, services/backend/package.json, services/backend/scripts/generate-bearer-token.js
You can run this script from anywhere in the repository.
From root: `$ node services/backend/generate-bearer-token.js --username test`
=> Add script to generate bearer token

services/backend/router.js, services/backend/src/assignments-controller.js, services/backend/src/courses-controller.js, services/backend/src/holidays-controller.js, services/backend/src/ping.js, services/backend/src/sections-controller.js, services/backend/src/tasks-controller.js, services/backend/src/terms-controller.js, services/backend/src/users-controller.js, services/backend/utils/auth.js, services/backend/utils/errors.js, services/backend/utils/request-validator.js, services/frontend/src/utils/api.js
BE: Add custom error classes for intentionally thrown errors
FE: Add an error wrapper to handle our intentional errors differently
=> Add better error handling to the backend

.github/workflows/deploy.yml
Didn't realize Gatsby generates a different file for each page. We'll need to add a new statement for each page we make
=> Fix access in deploy script

package-lock.json, services/frontend/package.json, services/frontend/src/components/assignments/assignment-editor.js, services/frontend/src/components/schedule/holiday-display.js, services/frontend/src/components/schedule/section-display.js, services/frontend/src/components/schedule/term-display.js, services/frontend/src/components/tasks/task-editor.js, services/frontend/src/globals/RootWrapper.js, services/frontend/src/globals/theme.js
Apparently we needed to use a specific version of @date-io/dayjs in order for it to work 😒
=> Set up fancy datepickers!

services/frontend/src/components/assignments/assignment-cell.js, services/frontend/src/components/assignments/assignment-editor.js, services/frontend/src/components/shared/controls/course-picker.js, services/frontend/src/components/shared/course-label.js, services/frontend/src/components/shared/index.js, services/frontend/src/components/tasks/task-cell.js, services/frontend/src/components/tasks/task-editor.js, services/frontend/src/globals/global.scss
- Add `CoursePicker` component
- Add it to the task and assignment pages
- Add course info to task and assignment cells
=> Add course picker to frontend

services/frontend/src/components/assignments/assignment-cell.js, services/frontend/src/components/assignments/assignment-editor.js, services/frontend/src/components/assignments/assignment-modal.js, services/frontend/src/components/assignments/assignments-list.js, services/frontend/src/components/assignments/subtasks-list.js, services/frontend/src/components/assignments/subtasks-list.scss, services/frontend/src/components/assignments/task-modal.js, services/frontend/src/components/schedule/course-editor.js, services/frontend/src/components/schedule/holiday-editor.js, services/frontend/src/components/schedule/section-editor.js, services/frontend/src/components/schedule/term-editor.js, services/frontend/src/components/shared/controls/course-picker.js, services/frontend/src/components/shared/controls/due-date-picker.js, services/frontend/src/components/shared/course-label.js, services/frontend/src/components/shared/editor.scss, services/frontend/src/components/shared/list.scss, services/frontend/src/components/tasks/assignment-preview.js, services/frontend/src/components/tasks/assignment-preview.module.scss, services/frontend/src/components/tasks/task-cell.js, services/frontend/src/components/tasks/task-editor.js, services/frontend/src/components/tasks/task-modal.js, services/frontend/src/components/tasks/task-modal.module.scss, services/frontend/src/components/tasks/tasks-list.js, services/frontend/src/components/tasks/tasks-list.module.scss, services/frontend/src/globals/global.scss, services/frontend/src/store/assignments.js, services/frontend/src/store/tasks.js
- Modals for creating assignments and tasks added
- Assignment and task editors both display subtask info
=> Subtask creation

services/frontend/src/components/shared/controls/course-picker.js, services/frontend/src/components/tasks/task-editor.js
- Automatically populate course picker for subtasks
- Disable course picker for subtasks
=> Automatically populate course for subtasks

.github/workflows/deploy.yml, package.json, packages/core/package.json
Forgot to include dependencies in the bootstrap, oops
=> Fix FE deployment

services/frontend/src/components/assignments/assignment-modal.js, services/frontend/src/components/assignments/assignments-list.js, services/frontend/src/components/assignments/assignments-page.js, services/frontend/src/components/tasks/assignment-preview.js, services/frontend/src/components/tasks/task-editor.js, services/frontend/src/components/tasks/task-editor.scss, services/frontend/src/components/tasks/task-modal.js, services/frontend/src/components/tasks/tasks-list.js, services/frontend/src/components/tasks/tasks-page.js
- Automatically select the title in creation modals, so you don't need to select it and delete it yourself
- When you create a new thing, automatically select it in the list
- In the task editor, if a task is a subtask show the related assignment where the course picker would normally be so it doesn't look so cluttered
=> Little QOL updates

packages/core/src/date-utils.js, packages/fe-shared/components/editor.js, services/mobile-frontend/src/components/shared/due-date-control.js, services/mobile-frontend/src/components/shared/list-item.js, services/mobile-frontend/src/components/shared/pickers/due-date-picker.js, services/mobile-frontend/src/components/tasks/new-task-modal.js, services/mobile-frontend/src/components/tasks/task-details.js, services/mobile-frontend/src/components/tasks/task-editor.js, services/mobile-frontend/src/globals/root.js
Make sure #93 is merged before reviewing this one too
Overview of changes:
- Modified `Editor` so it can be used for creation too. Then I merged the task detail editor and new task modal into `TaskEditor` so there's less duplicated code
- Created `DueDatePicker` (can also be used for assignments)
- Added the due date picker to the task editor, and animated it
=> Add date pickers for mobile tasks

packages/fe-shared/store/fetch-status.js, packages/fe-shared/store/reducers.js, services/frontend/.eslintrc.js, services/frontend/src/components/shared/navbar.js, services/mobile-frontend/src/components/shared/header.js
Fetch when the frontend receives focus, if data has not been fetched for over 5 minutes
=> Auto-fetch

services/backend/src/controllers/users-controller.js, services/backend/src/controllers/users-controller.test.js
Part of #124
Adds color preferences to users, so we can set them on the frontend and use custom colors!
=> Add primaryColor and accentColor properties to users

services/frontend/src/components/assignments/assignments-list.js, services/frontend/src/components/assignments/assignments-list.module.scss, services/frontend/src/components/shared/controls/fab.js, services/frontend/src/components/shared/navbar.js, services/frontend/src/components/shared/navbar.module.scss, services/frontend/src/components/shared/page.js, services/frontend/src/components/shared/page.module.scss, services/frontend/src/components/shared/sidebar.js, services/frontend/src/components/shared/sidebar.module.scss, services/frontend/src/components/shared/typography.js, services/frontend/src/components/tasks/tasks-list.js, services/frontend/src/components/tasks/tasks-list.module.scss, services/frontend/src/globals/global.scss, services/frontend/src/globals/theme.js
**Notable changes:**
1. Restyled the page wrapper
2. Added some global style overrides in theme.js
2. Added a custom FAB cuz I couldn't change elevation on the Mui one
3. Added a custom Typography class so we can make our own text styles
=> Started the web redesign

packages/fe-shared/components/editor.js, services/frontend/src/components/assignments/assignment-editor.js, services/frontend/src/components/assignments/assignment-editor.scss, services/frontend/src/components/shared/controls/action-button.js, services/frontend/src/components/shared/controls/action-button.module.scss, services/frontend/src/components/shared/controls/checkbox.js, services/frontend/src/components/shared/controls/checkbox.module.scss, services/frontend/src/components/shared/controls/course-picker.js, services/frontend/src/components/shared/controls/course-picker.module.scss, services/frontend/src/components/shared/controls/due-date-picker.js, services/frontend/src/components/shared/controls/due-date-picker.module.scss, services/frontend/src/components/shared/controls/input-group.js, services/frontend/src/components/shared/controls/input-group.module.scss, services/frontend/src/components/shared/controls/priority-picker.js, services/frontend/src/components/shared/controls/priority-picker.scss, services/frontend/src/components/shared/controls/tag-editor.js, services/frontend/src/components/shared/controls/tag-editor.module.scss, services/frontend/src/components/shared/controls/text-button.js, services/frontend/src/components/shared/controls/text-input.js, services/frontend/src/components/shared/controls/text-input.module.scss, services/frontend/src/components/shared/displays/priority-constants.js, services/frontend/src/components/shared/typography.js, services/frontend/src/components/tasks/assignment-preview.js, services/frontend/src/components/tasks/assignment-preview.module.scss, services/frontend/src/components/tasks/task-editor.js, services/frontend/src/components/tasks/task-editor.scss, services/frontend/src/globals/theme.js
1. Restyled task and assignment editors
2. Created InputGroup, ActionButton, TextButton, and TextInput
3. Updated styles for CoursePicker, DueDatePicker, TagEditor, and PriorityPicker
4. Added a few new Typography variants
5. Fixed the cursor jump bug that somehow showed up again
=> Update control styles on web

services/frontend/src/components/home/GoogleButton.js
Added a loading bar after hitting login on the home page
=> Adding feedback when a user tries to log in

services/frontend/src/components/shared/controls/checkbox.js
I think it might look better without them. What do you guys think?
=> Stop using course color for checkboxes

services/frontend/src/components/shared/controls/priority-picker.js, services/frontend/src/components/shared/controls/priority-picker.scss
Wrapped the picker in a container to avoid margin issues
=> Fix PriorityPicker padding bug

services/frontend/src/components/shared/controls/due-date-picker.js
Old logic from when we were using the Material UI pickers was causing the issue
=> Fix task page due date bug

services/frontend/src/components/shared/controls/course-picker.js, services/frontend/src/components/tasks/task-modal.js
Should make it feel a bit more 'intelligent'
=> adding default value of date picker to be assignment due date for subtasks

services/backend/src/controllers/verify-id-token.js, services/frontend/src/components/overview/overview-weekly.js, services/mobile-frontend/src/components/home/mobile-login-button.js
Honestly I am not sure why this is correct but this is the only setup that works. I tested it a bunch using a local backend
=> Fix mobile sign-in bug

services/frontend/src/components/shared/breadcrumbs-like.js, services/frontend/src/components/shared/controls/action-button.js, services/frontend/src/components/shared/controls/date-picker.js, services/frontend/src/components/shared/controls/fab.js, services/frontend/src/components/shared/controls/input-group.js, services/frontend/src/components/shared/controls/text-button.js, services/frontend/src/components/shared/list-header.js, services/frontend/src/components/shared/list-subheader.js, services/frontend/src/components/shared/typography.js, services/frontend/src/components/tasks/tasks-list.js
Nothing major, just getting rid of some annoying console errors
=> Minor bugfixes

packages/fe-shared/utils/scheduling-utils.js, services/frontend/src/components/overview/overview-schedule-list.js, services/frontend/src/components/overview/overview-schedule-list.module.scss, services/frontend/src/components/overview/overview-weekly.module.scss, services/frontend/src/components/shared/displays/empty-sticker.js
1. I think this fixes the weird shrinking behavior @prao3 was seeing. Lmk if this looks right to you / if it stretches to fill your full screen
2. Added "Nothing planned" for days with nothing, so it's a little clearer that this shows the next 7 days
3. Removed classes from the list if they already occurred (only affects today)
=> Overview updates

services/frontend/src/components/shared/controls/tag-editor.js, services/frontend/src/components/shared/controls/tag-editor.module.scss, services/frontend/src/components/tasks/task-cell.js, services/frontend/src/components/tasks/task-cell.module.scss
Now instead of a delete button on every tag, edit and delete buttons show up when you hover over tags.
=> Simplify tags in the task editor and make it so we can edit individual ones

packages/core/src/date-utils.js, packages/fe-shared/sorting/tasks.js, services/frontend/src/components/assignments/assignments-list.js, services/frontend/src/components/overview/overview-schedule-list.js, services/frontend/src/components/tasks/tasks-list.js, services/mobile-frontend/src/components/assignments/assignment-preview.js
Now instead of just saying "March 8th" it'll say "Monday, March 8th"
=> Update headers in lists to display the day of the week

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/lint-and-test.yml
=> chore: Reactivate

.github/workflows/deploy.yml, .github/workflows/lint-and-test-node.yml, .github/workflows/lint-and-test.yml, .github/workflows/pr.yml
=> fix: Use old node version

.github/workflows/pr.yml, .github/workflows/terraform.yml, infra/worker-role.tf
=> fix(infra): Import gha-worker role

infra/worker-role.tf
=> fix(infra): Remove unnecessary policy attachment

.github/workflows/pr.yml, .github/workflows/terraform.yml, infra/providers.tf, infra/terraform-state-bucket.tf, infra/worker-role.tf
=> chore(infra): Import terraform state bucket

.github/workflows/deploy.yml
Adding new infra workflow permissions
=> fix(ci): Fix deploy workflow permissions
